# Use uma imagem base oficial do Node.js
FROM node:20-alpine


# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie o package.json e o package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código da aplicação
COPY . .

# Gerar o Prisma Client
RUN npx prisma generate

# Exponha a porta em que a API irá rodar (certifique-se de que a API está configurada para rodar na porta 3001)
EXPOSE 3001

# Comando para iniciar a API
CMD ["npm", "run", "dev"]
